export const READ_PRODUCTS = 'READ_PRODUCTS';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const SHOW_DELETE_MODAL = 'SHOW_DELETE_MODAL';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const CREATE_PRODUCT = 'CREATE_PRODUCT';

export const READ_CATEGORY = 'READ_CATEGORY';